name: ci-check
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: "Installing node 18"
        with:
          node-version: '18'
      - uses: borales/actions-yarn@v2.3.0
        name: "Dependencies"
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        name: "Runing tests"
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.3.0
        name: "Build"
        with:
          cmd: build