
name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main]

jobs:
  ci:
    name: 'Test (${{ matrix.node-version }})'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18']
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/cache@v2
        id: loom-cache
        name: Restore loom cache
        with:
          path: |
            .loom
          key: ${{ runner.os }}-loom-${{ matrix.node-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-loom-${{ matrix.node-version }}
      - uses: borales/actions-yarn@v2.3.0
        name: "Yarn install"
        with:
          cmd: install --frozen-lockfile
      - uses: borales/actions-yarn@v2.3.0
        name: "Runing tests"
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.3.0
        name: "Build"
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        if: startsWith(github.ref, 'refs/tags/v')
        name: "Publish"
        with:
          cmd: publish:npm